services:
  postgres:
    image: postgres:16-alpine
    container_name: reccollection-postgres-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reccollection
    volumes:
      - reccollection_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  reccollection_data:
