name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd app/frontend && bun install

      - name: Lint
        run: cd app/frontend && bun run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd app/frontend && bun install

      - name: Run unit tests
        run: cd app/frontend && bun run test || echo "No tests found or tests failed, but continuing"

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        if: success() || failure() # Upload even if tests fail
        with:
          name: coverage
          path: app/frontend/coverage/

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          cd app/frontend && bun install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: cd app/frontend && bun run build
          start: cd app/frontend && bun run preview
          wait-on: "http://localhost:4173"
          browser: chrome
          working-directory: .
          config-file: cypress.config.ts

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  build:
    runs-on: ubuntu-latest
    needs: [lint, test, e2e]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd app/frontend && bun install

      - name: Build
        run: cd app/frontend && bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: app/frontend/dist/
